# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(default='', max_length=30)),
                ('provincia', models.CharField(default='', max_length=30)),
                ('ciudad', models.CharField(default='', max_length=30)),
                ('calle', models.CharField(default='', max_length=30)),
                ('altura', models.CharField(default='', max_length=30)),
                ('entre_calle', models.CharField(default='', max_length=30)),
                ('piso', models.CharField(default='', max_length=30)),
                ('depto', models.CharField(default='', max_length=30)),
                ('codigo_postal', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('mail', models.CharField(default='', max_length=30)),
                ('web', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_area', models.IntegerField(default='0000')),
                ('telefono', models.IntegerField(default='0000')),
                ('tipo', models.CharField(choices=[('C', 'Celular'), ('F', 'Fijo')], max_length=10)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor'),
        ),
    ]
