# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='web',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
