# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20160201_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='altura',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='depto',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='entre_calle',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='piso',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='provincia',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_fijo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='Telefono',
        ),
    ]
